### ISSUE TITLE
Update Sermon Manager Import on Wordpress Page

### ISSUE THREAD

**Issue by hermify** [khornberg/sermon-manager-import#15]
Hi there,
could you please update the official Wordpress Plugin?
Or how can i do this?

And change the compatibility to Wordpress 4.9.5 and PHP 7

Thanks!

**Comment by khornberg** [comment]
I will try to get to this in the next few weeks. I'm not quite sure how to it any more.

Thank you by the way for all the contributions. I'm glad someone else is finding use in the plugin.

**Comment by khornberg** [comment]
@hermify I forgot to change the compatibility. But I did find that I have a deploy script in this repo so that was nice. I've pushed the updates otherwise. Thank you for all your work on this

**Comment by khornberg** [comment]
Looks like the compatibility updated. I'm not sure where to put the PHP version.
