### ISSUE TITLE
Array Issue

### ISSUE THREAD

**Issue by vtyler** [khornberg/sermon-manager-import#5]
Any reason why I would get this error:

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\wamp\www\church_sermons\wp-content\plugins\sermon-manager-import\class-sermon-manager-import.php on line 853

As well it always seems to leave a sermon to be uploaded behind?

**Comment by khornberg** [comment]
When you click the `Details` button on the `Import Sermons` page, does the `Import As` Section populate with anything?

I am testing on 4.2.2 and have run into a very similar issue.

**Comment by khornberg** [comment]
Have you saved the settings? If you have not, try going to Sermons->Import Options and pressing the `Save Changes` button.

In my tests, I've needed to do so to reproduce this problem.

**Comment by vtyler** [comment]
The Import As is blank....except for the publish date.
Made me think I didn't have any ID3 information in my mp3 so the next time I added it and I didn't get the error. (I did save the settings before I uploaded though) All though I get a new one:

Warning: Missing argument 2 for SermonManagerImport::get_dates(), called in D:\home\site\wwwroot\wp-content\plugins\sermon-manager-import\class-sermon-manager-import.php on line 636 and defined in D:\home\site\wwwroot\wp-content\plugins\sermon-manager-import\class-sermon-manager-import.php on line 793

**Comment by vtyler** [comment]
To fix the date one...looks like you just need to add a second parameter to line 636 in the above file:

			$date = $this->get_dates($audio[$this->options['date']]); to
			$date = $this->get_dates($audio[$this->options['date']],$file_name); 

not sure if the $file_name makes sense there or not though

**Comment by khornberg** [comment]
I've [pushed an update that fixes the get_dates() warning](https://github.com/khornberg/sermon-manager-import/blob/master/class-sermon-manager-import.php#L632).

I've also added a warning if the file does not contain any ID3 tags.

Let me know how 0.2.4 works for you.

**Comment by vtyler** [comment]
Perfect got the warning and the sermon was published!
No errors on the date function now either.

Thanks.

**Comment by vtyler** [comment]
Maybe change the color on the warning from Red to Yellow? Yellow is more of a warning and at first when I saw the red I thought maybe it wasn't going to import but other than that it's good now.

**Comment by khornberg** [comment]
Thanks for the feedback. 
It could be yellow but the box changes when a class of update-nag is applied.
